services:
  mysql:
    image: mysql:8.0.40
    ports:
      - "3309:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql-volume:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=10000

volumes:
  mysql-volume:
